### ISSUE TITLE
Use `virtual-schema-common-lua`

### ISSUE THREAD

**Issue by redcatbear** [exasol/row-level-security-lua#106]
## Situation

Recently we started extracting the common part for all Lua-based Virtual Schemas into a separate library. We should now use that library to prove it still works and to remove code duplication.

## Tasks

- [x] exasol/virtual-schema-common-lua#1
- [ ] Remove code duplication from this repository
- [ ] Remove specification duplication from this repository
- [ ] Add VSLC as LuaRocks dependency
- [ ] Get all tests green
